# Generated by Django 5.2 on 2025-06-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_gender_alter_accessrequest_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalWallet',
            new_name='HosmedicalWallet',
        ),
    ]
