# Generated by Django 5.2 on 2025-06-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_medicalwallet_hosmedicalwallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HosmedicalWallet',
        ),
    ]
