# Generated by Django 5.2 on 2025-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_userwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='private_key',
            new_name='encrypted_private_key',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='iv',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
