# Generated by Django 5.2 on 2025-06-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_rename_private_key_userwallet_encrypted_private_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='encrypted_private_key',
            new_name='private_key',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='iv',
        ),
    ]
